name: tagpr
on:
  push:
    branches:
    - "main"
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.x
    - name: Generate token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
    - name: checkout
      uses: actions/checkout@v3
      with:
        token: ${{ steps.generate_token.outputs.token }}
    - name: tagpr
      run: |
        make install
        echo '::echo::on'
        tagpr
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
